#!/usr/bin/env node
/**
 * brand-surface.mjs — Phase 3 of stardust:extract, mechanical aggregation per
 * extract/reference/brand-surface.md over stardust/current/pages/*.json (+ _fonts.json, harvested CSS).
 * Writes stardust/current/_brand-extraction.json. Never invents: every value cites its source pages/selectors.
 * usage: node stardust/scripts/brand-surface.mjs [--out stardust/current] [--home index]
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
const args = { out: 'stardust/current', home: 'index', origin: 'https://www.sparebank1.no' };
for (let i = 2; i < process.argv.length; i++) { const k = process.argv[i]; if (k === '--out') args.out = process.argv[++i]; else if (k === '--home') args.home = process.argv[++i]; else if (k === '--origin') args.origin = process.argv[++i]; }
const pagesDir = path.join(args.out, 'pages');
const pages = readdirSync(pagesDir).filter(f => f.endsWith('.json')).map(f => JSON.parse(readFileSync(path.join(pagesDir, f), 'utf8')));
const home = pages.find(p => p.slug === args.home);
const notes = [];
// ---------- color utils ----------
const parseColor = (s) => { if (!s) return null; const m = s.match(/rgba?\(\s*(\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\s*\)/); if (m) { const a = m[4] === undefined ? 1 : +m[4]; if (a === 0) return null; return { r: +m[1], g: +m[2], b: +m[3], a }; } const h = s.match(/^#([0-9a-f]{3,8})$/i); if (h) { let x = h[1]; if (x.length === 3) x = x.split('').map(c => c + c).join(''); return { r: parseInt(x.slice(0, 2), 16), g: parseInt(x.slice(2, 4), 16), b: parseInt(x.slice(4, 6), 16), a: 1 }; } if (s === 'transparent') return null; return null; };
const hex = (c) => '#' + [c.r, c.g, c.b].map(v => v.toString(16).padStart(2, '0')).join('');
const toLab = ({ r, g, b }) => { const f = (v) => { v /= 255; return v > 0.04045 ? ((v + 0.055) / 1.055) ** 2.4 : v / 12.92; }; const [R, G, B] = [f(r), f(g), f(b)]; let x = (R * 0.4124 + G * 0.3576 + B * 0.1805) / 0.95047, y = (R * 0.2126 + G * 0.7152 + B * 0.0722), z = (R * 0.0193 + G * 0.1192 + B * 0.9505) / 1.08883; const g2 = (t) => t > 0.008856 ? Math.cbrt(t) : 7.787 * t + 16 / 116; [x, y, z] = [g2(x), g2(y), g2(z)]; return { L: 116 * y - 16, a: 500 * (x - y), b: 200 * (y - z) }; };
const dE = (c1, c2) => { const a = toLab(c1), b = toLab(c2); return Math.hypot(a.L - b.L, a.a - b.a, a.b - b.b); };
const sat = (c) => Math.max(c.r, c.g, c.b) - Math.min(c.r, c.g, c.b);
const lum = (c) => 0.2126 * c.r + 0.7152 * c.g + 0.0722 * c.b;
// ---------- palette ----------
const colorTable = new Map(); // hex -> {c, occ, usedAs:Set, selectors:Set, pages:Map}
const addColor = (str, usedAs, selector, slug, w = 1) => { const c = parseColor(str); if (!c) return; const key = hex(c); let e = colorTable.get(key); if (!e) { e = { c, occ: 0, usedAs: new Set(), selectors: new Set(), pages: new Map() }; colorTable.set(key, e); } e.occ += w; e.usedAs.add(usedAs); if (selector && e.selectors.size < 6) e.selectors.add(selector); e.pages.set(slug, (e.pages.get(slug) || 0) + w); };
for (const p of pages) {
  for (const s of p.perSectionStyle || []) { const area = Math.max(1, Math.round((s.rect?.height || 300) / 100)); addColor(s.background?.color, 'background', s.sectionRef, p.slug, area); addColor(s.text?.dominantColor, 'text', s.sectionRef, p.slug, 2); }
  for (const h of p.headings || []) addColor(h.style?.color, 'text', `h${h.level}`, p.slug, 1);
  for (const c of p.ctas || []) { addColor(c.style?.backgroundColor, 'background', c.domPath?.split(' > ').pop(), p.slug, 1); addColor(c.style?.color, 'text', c.domPath?.split(' > ').pop(), p.slug, 1); const bm = (c.style?.border || '').match(/rgba?\([^)]+\)/); if (bm && !/^0px/.test(c.style.border)) addColor(bm[0], 'border', c.domPath?.split(' > ').pop(), p.slug, 1); }
  addColor(p.textRendering?.bodyBackground, 'background', 'body', p.slug, 3); addColor(p.textRendering?.bodyColor, 'text', 'body', p.slug, 3);
}
// cluster ΔE<5
const entries = [...colorTable.entries()].sort((a, b) => b[1].occ - a[1].occ);
const clusters = [];
for (const [k, e] of entries) { const hit = clusters.find(cl => dE(cl.rep.c, e.c) < 5); if (hit) { hit.occ += e.occ; for (const u of e.usedAs) hit.usedAs.add(u); for (const s of e.selectors) if (hit.selectors.size < 6) hit.selectors.add(s); for (const [pg, n] of e.pages) hit.pages.set(pg, (hit.pages.get(pg) || 0) + n); hit.members.push(k); } else clusters.push({ rep: e, key: k, occ: e.occ, usedAs: new Set(e.usedAs), selectors: new Set(e.selectors), pages: new Map(e.pages), members: [k] }); }
clusters.sort((a, b) => b.occ - a.occ);
const ctaBgCount = new Map(); for (const p of pages) for (const c of p.ctas || []) { if (c.inHeader || c.inFooter) continue; const col = parseColor(c.style?.backgroundColor); if (!col || sat(col) < 30) continue; const k = hex(col); ctaBgCount.set(k, (ctaBgCount.get(k) || 0) + 1); }
const clusterOf = (k) => clusters.find(cl => cl.members.includes(k)) || clusters.find(cl => dE(cl.rep.c, parseColor(k)) < 5);
const ctaRank = [...ctaBgCount.entries()].sort((a, b) => b[1] - a[1]).map(([k]) => clusterOf(k)).filter(Boolean);
const roles = new Map();
const bgClusters = clusters.filter(cl => cl.usedAs.has('background'));
const textClusters = clusters.filter(cl => cl.usedAs.has('text'));
if (bgClusters[0]) roles.set(bgClusters[0].key, 'background');
const textPrimary = textClusters.find(cl => lum(cl.rep.c) < 120 && !roles.has(cl.key)); if (textPrimary) roles.set(textPrimary.key, 'text-primary');
const textInverse = textClusters.find(cl => lum(cl.rep.c) > 240 && !roles.has(cl.key)); if (textInverse) roles.set(textInverse.key, 'text-inverse');
if (ctaRank[0] && !roles.has(ctaRank[0].key)) roles.set(ctaRank[0].key, 'primary');
if (ctaRank[1] && !roles.has(ctaRank[1].key)) roles.set(ctaRank[1].key, 'secondary');
const surface = bgClusters.find(cl => !roles.has(cl.key) && lum(cl.rep.c) > 225 && sat(cl.rep.c) < 30 && cl.occ >= 20); if (surface) roles.set(surface.key, 'surface');
const border = clusters.find(cl => cl.usedAs.has('border') && !roles.has(cl.key)); if (border) roles.set(border.key, 'border');
let accentN = 1; for (const cl of clusters) { if (roles.has(cl.key)) continue; if (sat(cl.rep.c) >= 30 && cl.occ >= 5) roles.set(cl.key, `accent-${accentN++}`); }
const textSecondary = textClusters.find(cl => !roles.has(cl.key) && lum(cl.rep.c) >= 60 && lum(cl.rep.c) < 170 && sat(cl.rep.c) < 40); if (textSecondary) roles.set(textSecondary.key, 'text-secondary');
const paletteAll = clusters.filter(cl => roles.has(cl.key)).map(cl => ({ role: roles.get(cl.key), value: cl.key, occurrences: Math.round(cl.occ), sourceSelectors: [...cl.selectors].slice(0, 4), sources: [...cl.pages.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3).map(([s]) => s), usedAs: [...cl.usedAs], clusterMembers: cl.members.length > 1 ? cl.members.slice(0, 6) : undefined }));
const roleOrder = ['background', 'surface', 'text-primary', 'text-secondary', 'text-inverse', 'primary', 'secondary', 'border'];
paletteAll.sort((a, b) => { const ia = roleOrder.indexOf(a.role), ib = roleOrder.indexOf(b.role); return (ia < 0 ? 100 : ia) - (ib < 0 ? 100 : ib) || b.occurrences - a.occurrences; });
const palette = paletteAll.slice(0, 8); if (paletteAll.length > 8) notes.push(`palette capped at 8; dropped: ${paletteAll.slice(8).map(p => `${p.value} (${p.role}, ${p.occurrences})`).join(', ')}`);
// ---------- type ----------
const fam = (s) => (s || '').split(',')[0].replace(/["']/g, '').trim();
const headingFamCount = new Map(); for (const p of pages) for (const h of p.headings || []) { const f = fam(h.style?.fontFamily); if (f) headingFamCount.set(f, (headingFamCount.get(f) || 0) + 1); }
const headingFamily = [...headingFamCount.entries()].sort((a, b) => b[1] - a[1])[0]?.[0];
const headingStack = pages.flatMap(p => p.headings || []).find(h => fam(h.style?.fontFamily) === headingFamily)?.style.fontFamily;
const bodyFamCount = new Map(); for (const p of pages) { const f = fam(p.textRendering?.bodyFontFamily); if (f) bodyFamCount.set(f, (bodyFamCount.get(f) || 0) + 1); }
const bodyFamily = [...bodyFamCount.entries()].sort((a, b) => b[1] - a[1])[0]?.[0]; const bodyStack = pages.find(p => fam(p.textRendering?.bodyFontFamily) === bodyFamily)?.textRendering.bodyFontFamily;
const levels = {}; for (const p of pages) for (const h of p.headings || []) { if (!h.style) continue; const L = levels[h.level] = levels[h.level] || new Map(); const k = `${h.style.fontSize}|${h.style.fontWeight}|${h.style.lineHeight}|${h.style.letterSpacing}`; const e = L.get(k) || { n: 0, pages: new Set(), fontSize: h.style.fontSize, fontWeight: h.style.fontWeight, lineHeight: h.style.lineHeight, letterSpacing: h.style.letterSpacing, textTransform: h.style.textTransform }; e.n++; e.pages.add(p.slug); L.set(k, e); }
const perLevel = Object.entries(levels).map(([lvl, m]) => { const best = [...m.values()].map(e => ({ ...e, score: parseFloat(e.fontSize) * ((+e.fontWeight || 400) / 400) * Math.sqrt(e.n) })).sort((a, b) => b.score - a.score)[0]; return { level: +lvl, fontSize: best.fontSize, fontWeight: +best.fontWeight, lineHeight: best.lineHeight, letterSpacing: best.letterSpacing, textTransform: best.textTransform, count: best.n, pages: [...best.pages].slice(0, 3), variants: m.size }; }).sort((a, b) => a.level - b.level);
const sizesPx = perLevel.map(l => parseFloat(l.fontSize)).filter(Boolean);
const ratios = []; for (let i = 0; i < sizesPx.length - 1; i++) ratios.push(+(sizesPx[i] / sizesPx[i + 1]).toFixed(3));
const scales = { 'minor-second': 1.067, 'major-second': 1.125, 'minor-third': 1.2, 'major-third': 1.25, 'perfect-fourth': 1.333, 'augmented-fourth': 1.414, 'perfect-fifth': 1.5, golden: 1.618 };
let matched = null; for (const [name, r] of Object.entries(scales)) if (ratios.length && ratios.every(x => Math.abs(x - r) <= 0.025)) matched = name;
const bodySizes = new Map(); for (const p of pages) { if (!p.textRendering?.bodyFontSize) continue; const k = `${p.textRendering.bodyFontSize}|${p.textRendering.bodyLineHeight}`; bodySizes.set(k, (bodySizes.get(k) || 0) + 1); }
const fontsJson = existsSync(path.join(args.out, '_fonts.json')) ? JSON.parse(readFileSync(path.join(args.out, '_fonts.json'), 'utf8')) : { files: [], fontFaces: [] };
const openFamilies = /^(roboto|inter|open sans|lato|montserrat|poppins|source sans|noto|raleway|nunito|work sans|dm sans|ibm plex|merriweather|playfair|oswald|rubik|manrope|karla|figtree)/i;
const seenBase = new Set();
const files = fontsJson.files.filter(f => { const b = path.basename(new URL(f.url).pathname); if (seenBase.has(b)) return false; seenBase.add(b); return true; }).map(f => { const base = path.basename(new URL(f.url).pathname); const rule = fontsJson.fontFaces.find(r => (r.src || '').includes(base)); const family = rule?.family || (/^KFO|^1Pt/.test(base) ? 'Roboto (Google Fonts static, family inferred from file-id prefix; @font-face rule cross-origin — not readable)' : null); return { url: f.url, family, weight: rule ? +rule.weight || rule.weight : null, style: rule?.style || null, unicodeRange: rule?.unicodeRange || null, localPath: f.localPath, bytes: f.bytes, sourceCssRule: rule?.cssText || null, licensingFlag: family ? (/atlas-icon/i.test(family) ? 'private' : openFamilies.test(family) ? 'open' : 'private') : null }; });
const textRenderingMode = (() => { const m = new Map(); for (const p of pages) { const k = JSON.stringify({ tr: p.textRendering?.textRendering, sm: p.textRendering?.webkitFontSmoothing, syn: p.textRendering?.fontSynthesis, kern: p.textRendering?.fontKerning, html: p.textRendering?.htmlFontSize }); m.set(k, (m.get(k) || 0) + 1); } return JSON.parse([...m.entries()].sort((a, b) => b[1] - a[1])[0][0]); })();
const type = { headingFamily: { name: headingFamily, stack: headingStack, weights: [...new Set(perLevel.map(l => l.fontWeight))].sort(), sizes: perLevel.map(l => l.fontSize), lineHeights: perLevel.map(l => l.lineHeight), letterSpacing: [...new Set(perLevel.map(l => l.letterSpacing))], sourceSelectors: perLevel.map(l => `h${l.level}`), perLevel }, bodyFamily: { name: bodyFamily, stack: bodyStack, weights: [400, 500], sizes: [...bodySizes.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3).map(([k]) => k.split('|')[0]), lineHeights: [...bodySizes.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3).map(([k]) => k.split('|')[1]), letterSpacing: ['normal'], sourceSelectors: ['body', 'p'] }, monoFamily: null, scaleRatio: matched ? scales[matched] : null, scaleAudit: { kind: matched ? 'modular' : 'ad-hoc', ratios, matchedScale: matched }, loadStrategy: fontsJson.fontFaces[0]?.display || null, textRendering: textRenderingMode, files };
// ---------- spacing ----------
const px = (s) => { const m = (s || '').match(/-?[\d.]+px/g); return m ? m.map(parseFloat) : []; };
const padCount = new Map(), gapCount = new Map(); for (const p of pages) for (const s of p.perSectionStyle || []) { for (const v of px(s.spacing?.paddingBlock)) if (v > 0) padCount.set(v, (padCount.get(v) || 0) + 1); for (const v of px(s.spacing?.gap)) if (v > 0) gapCount.set(v, (gapCount.get(v) || 0) + 1); }
const padVals = [...padCount.entries()].filter(([, n]) => n >= 3).map(([v]) => v).sort((a, b) => a - b);
const baseUnit = padVals.length && padVals.every(v => v % 8 === 0) ? 8 : padVals.length && padVals.every(v => v % 4 === 0) ? 4 : null;
const containerCount = new Map(); for (const p of pages) { const k = p.containerModel?.maxWidthMode; if (k && /px$/.test(k)) containerCount.set(k, (containerCount.get(k) || 0) + 1); }
const spacing = { baseUnit, scale: padVals.slice(0, 14), sectionPadding: [...padCount.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] + 'px', containerMaxWidth: [...containerCount.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] || null, containerCandidates: [...containerCount.entries()].sort((a, b) => b[1] - a[1]).slice(0, 4), gridGap: [...gapCount.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] + 'px', paddingOccurrences: Object.fromEntries([...padCount.entries()].sort((a, b) => b[1] - a[1]).slice(0, 12)) };
// ---------- motifs ----------
const radCount = new Map(), radPages = new Map(); const addRad = (v, slug) => { if (!v) return; const first = v.split(' ')[0]; if (!first || first === '0px') return; radCount.set(first, (radCount.get(first) || 0) + 1); const s = radPages.get(first) || new Set(); s.add(slug); radPages.set(first, s); };
for (const p of pages) { for (const c of p.ctas || []) addRad(c.style?.borderRadius, p.slug); for (const s of p.perSectionStyle || []) addRad(s.borderRadius, p.slug); }
const radSorted = [...radCount.entries()].sort((a, b) => b[1] - a[1]);
const isPill = (v) => parseFloat(v) >= 100 || /%/.test(v);
const nonPill = radSorted.filter(([v]) => !isPill(v));
const shadowCount = new Map(); for (const p of pages) { for (const c of p.ctas || []) if (c.style?.boxShadow && c.style.boxShadow !== 'none') shadowCount.set(c.style.boxShadow, (shadowCount.get(c.style.boxShadow) || 0) + 1); for (const s of p.perSectionStyle || []) for (const sh of s.shadowsUsed || []) shadowCount.set(sh, (shadowCount.get(sh) || 0) + 1); }
const gradCount = new Map(); for (const p of pages) for (const b of p.media?.cssBackgrounds || []) if (b.gradient) gradCount.set(b.gradient, (gradCount.get(b.gradient) || 0) + 1);
const patterns = [];
const heroImgPages = pages.filter(p => (p.perSectionStyle || [])[0]?.background?.hasImage).length; if (heroImgPages) patterns.push({ name: 'hero-with-illustration', evidence: `${heroImgPages}/${pages.length} pages open with a full-width colored hero carrying imagery (perSectionStyle[0].background.hasImage)` });
const gridPages = pages.filter(p => (p.components?.grids?.count || 0) > 0).length; if (gridPages) patterns.push({ name: 'card-grid', evidence: `${gridPages}/${pages.length} pages contain ≥1 equal-width grid/flex-wrap group (components.grids)` });
const accPages = pages.filter(p => (p.components?.accordions?.count || 0) > 0).length; if (accPages) patterns.push({ name: 'faq-accordion', evidence: `${accPages}/${pages.length} pages carry an accordion (components.accordions)` });
const ctaBandPages = pages.filter(p => (p.components?.ctaBand?.count || 0) > 0).length; if (ctaBandPages) patterns.push({ name: 'cta-band', evidence: `${ctaBandPages}/${pages.length} pages contain a heading+CTA-dominated band (landmarks purpose=cta-band)` });
const bcPages = pages.filter(p => (p.components?.breadcrumbs?.count || 0) > 0).length; if (bcPages) patterns.push({ name: 'breadcrumbs', evidence: `${bcPages}/${pages.length} pages` });
patterns.push({ name: 'nav-mega', evidence: `home header exposes ${home?.links?.internal?.filter(l => l.region === 'header').length} internal links (mega-menu under 6 top-level items)` });
patterns.push({ name: 'footer-mega', evidence: `home footer exposes ${home?.links?.internal?.filter(l => l.region === 'footer').length} internal links in ${home?.landmarks?.find(l => l.tag === 'footer')?.children?.length} column groups` });
const motifs = { borderRadius: { primary: nonPill[0]?.[0] || null, secondary: nonPill[1]?.[0] || null, pill: radSorted.find(([v]) => isPill(v))?.[0] || null, primarySources: [...(radPages.get(nonPill[0]?.[0]) || [])].slice(0, 3), occurrences: Object.fromEntries(radSorted.slice(0, 8)) }, shadows: [...shadowCount.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3).map(([value, n]) => ({ value, occurrences: n, uses: 'cards/buttons (observed on CTAs and section descendants)' })), gradients: [...gradCount.entries()].sort((a, b) => b[1] - a[1]).slice(0, 4).map(([value, n]) => ({ value, occurrences: n, uses: 'section background layer' })), patterns };
// ---------- component style (buttons from CTA clusters) ----------
const btnClusters = new Map(); for (const p of pages) for (const c of p.ctas || []) { if (c.inHeader || c.inFooter) continue; const bg = parseColor(c.style?.backgroundColor); const fg = parseColor(c.style?.color); if (!fg) continue; const k = `${bg ? hex(bg) : 'transparent'}|${hex(fg)}|${(c.style.borderRadius || '').split(' ')[0]}|${c.style.border && !/^0px/.test(c.style.border) ? c.style.border.split(' ').slice(0, 2).join(' ') : 'none'}`; const e = btnClusters.get(k) || { n: 0, sample: c, pages: new Set(), labels: new Set() }; e.n++; e.pages.add(p.slug); if (e.labels.size < 5 && c.label) e.labels.add(c.label); btnClusters.set(k, e); }
const btnRank = [...btnClusters.entries()].filter(([k]) => !k.startsWith('transparent') || k.split('|')[3] !== 'none').sort((a, b) => b[1].n - a[1].n);
const btnSpec = (e) => ({ background: parseColor(e.sample.style.backgroundColor) ? hex(parseColor(e.sample.style.backgroundColor)) : 'transparent', color: hex(parseColor(e.sample.style.color)), borderRadius: e.sample.style.borderRadius, padding: e.sample.style.padding, fontWeight: e.sample.style.fontWeight, fontSize: e.sample.style.fontSize, fontFamily: e.sample.style.fontFamily, border: e.sample.style.border, shadow: e.sample.style.boxShadow === 'none' ? null : e.sample.style.boxShadow, textTransform: e.sample.style.textTransform, letterSpacing: e.sample.style.letterSpacing, occurrences: e.n, pages: e.pages.size, sampleLabels: [...e.labels], hoverDelta: null });
const componentStyle = { buttons: { primary: btnRank[0] ? btnSpec(btnRank[0][1]) : null, secondary: btnRank[1] ? btnSpec(btnRank[1][1]) : null, ghost: btnRank[2] ? btnSpec(btnRank[2][1]) : null, allVariants: btnRank.slice(0, 8).map(([k, e]) => ({ key: k, ...btnSpec(e) })) }, dualCTAPattern: (() => { const h = home?.landmarks?.find(l => l.tag === 'main')?.children?.[0]; return h ? 'observed: hero carries primary filled CTA; secondary CTAs appear as outlined/white variants on dark bands' : null; })(), cards: { borderRadius: nonPill[0]?.[0] || null, shadow: motifs.shadows[0]?.value || null, note: 'card padding/border not captured per element by the style pass; radius/shadow are cross-page modes' }, inputs: { note: 'input styles not captured (search field in header only on most pages); lift from source CSS at recreation time' } };
// ---------- system components ----------
const fp = (p, tag) => { const lm = (p.landmarks || []).find(l => l.tag === tag); if (!lm) return null; const heads = (lm.children || []).flatMap(c => c.body?.length ? [] : []).length; const links = (p.links?.internal || []).filter(l => l.region === (tag === 'header' ? 'header' : 'footer')).map(l => l.text).filter(Boolean); const ctas = (p.ctas || []).filter(c => tag === 'header' ? c.inHeader : c.inFooter).map(c => c.label).filter(Boolean); return { links: [...new Set(links)], ctas: [...new Set(ctas)], key: JSON.stringify([...new Set(links)].slice(0, 30)) }; };
const sys = [];
for (const tag of ['header', 'footer']) { const groups = new Map(); for (const p of pages) { const f = fp(p, tag); if (!f) continue; const g = groups.get(f.key) || { pages: [], f }; g.pages.push(p.slug); groups.set(f.key, g); } for (const g of [...groups.values()].sort((a, b) => b.pages.length - a.pages.length)) { if (g.pages.length >= Math.min(3, Math.ceil(pages.length / 2))) sys.push({ name: `site-${tag}${sys.some(s => s.kind === tag) ? '-variant-' + (sys.filter(s => s.kind === tag).length + 1) : ''}`, kind: tag, occurrences: g.pages.length, headingSequence: g.f.links.slice(0, 12), ctaLabels: g.f.ctas.slice(0, 6), exampleSlug: g.pages.includes(args.home) ? args.home : g.pages[0], exampleSelector: tag, examplePages: g.pages.slice(0, 6), linkCount: g.f.links.length }); } }
const bgUse = new Map(); for (const p of pages) for (const b of p.media?.cssBackgrounds || []) if (b.url && !b.url.startsWith('data:')) { const e = bgUse.get(b.url) || { pages: new Set(), sample: b }; e.pages.add(p.slug); bgUse.set(b.url, e); }
for (const [url, e] of [...bgUse.entries()].filter(([, e]) => e.pages.size >= 2).sort((a, b) => b[1].pages.size - a[1].pages.size).slice(0, 6)) sys.push({ name: `background-motif:${path.basename(new URL(url).pathname)}`, kind: 'background-motif', occurrences: e.pages.size, url, exampleBlock: { domPath: e.sample.domPath, boundingClientRect: e.sample.boundingClientRect, backgroundSize: e.sample.backgroundSize, backgroundPosition: e.sample.backgroundPosition }, examplePages: [...e.pages].slice(0, 6) });
// ---------- icon font (from harvested CSS) ----------
let iconFont = null; { const cssDir = path.join(args.out, 'assets', 'css'); const glyphs = new Map(); let fam = null; for (const f of existsSync(cssDir) ? readdirSync(cssDir) : []) { const css = readFileSync(path.join(cssDir, f), 'utf8'); for (const m of css.matchAll(/\.([a-zA-Z0-9_-]*icon[a-zA-Z0-9_-]*)::?before\{content:"\\([0-9a-f]{3,5})"/g)) if (!glyphs.has(m[1])) glyphs.set(m[1], { class: m[1], codepoint: '\\' + m[2].toUpperCase(), name: (m[1].match(/icon-(.+)$/) || [])[1] || null, source: f }); const fm = css.match(/@font-face\{[^}]*font-family:"?(atlas-icon)"?[^}]*\}/); if (fm) fam = fm[1]; } if (glyphs.size) iconFont = { family: fam || 'atlas-icon', localPath: files.find(f => /atlas-icon/.test(f.url))?.localPath || null, sourceCss: fontsJson.fontFaces.find(r => /atlas-icon/.test(r.family))?.cssText || null, glyphCount: glyphs.size, glyphs: [...glyphs.values()], note: 'table parsed from the harvested source CSS (class→codepoint); per-page usage not recorded' }; }
// ---------- voice ----------
const heroImage = (() => { if (!home) return null; const cands = []; for (const i of home.media?.images || []) if (i.visible && i.rect && i.rect.top < 800 && i.rect.width * i.rect.height >= 100000) cands.push({ url: i.currentSrc || i.src, alt: i.alt, source: 'img', domPath: i.domPath, rect: i.rect, area: i.rect.width * i.rect.height }); for (const b of home.media?.cssBackgrounds || []) if (b.url && b.boundingClientRect && b.boundingClientRect.y < 800 && b.boundingClientRect.width * b.boundingClientRect.height >= 100000) cands.push({ url: b.url, alt: null, source: b.domPath.includes('::') ? 'css-pseudo-background' : 'css-background', domPath: b.domPath, rect: b.boundingClientRect, area: b.boundingClientRect.width * b.boundingClientRect.height }); cands.sort((a, b) => b.area - a.area || (a.source === 'img' ? -1 : 1)); const w = cands.filter(c => { const ar = c.rect.width / c.rect.height; return ar >= 0.3 && ar <= 3; })[0]; if (!w) notes.push('voice.heroImage: no candidate ≥100k px² in the first viewport on home (hero is an illustration/UI-card composition)'); return w ? { url: w.url, alt: w.alt, source: w.source, domPath: w.domPath, localPath: null, rect: w.rect } : null; })();
const heroMedium = (() => { const v = (home?.media?.videos || []).find(v => v.rect && v.rect.top < 800); return v ? { kind: 'video', mechanism: 'video-file', src: v.src, domPath: v.domPath, loader: null, rect: v.rect } : null; })();
const mainCtas = (home?.ctas || []).filter(c => !c.inHeader && !c.inFooter && c.label);
const navItems = [...new Set((home?.ctas || []).filter(c => c.inHeader && c.tag === 'button' && c.label && c.label.length < 20 && !/search|menu|close/i.test(c.label)).map(c => c.label))].slice(0, 10);
const footerHeadings = [...new Set((home?.headings || []).filter(h => /footer/i.test(h.domPath || '')).map(h => h.text))];
const ctaLabelCount = new Map(); for (const p of pages) for (const c of p.ctas || []) { const l = (c.label || '').trim(); if (!l || l.length > 40) continue; const k = l.toLowerCase(); const e = ctaLabelCount.get(k) || { label: l, total: 0, pages: new Set() }; e.total++; e.pages.add(p.slug); ctaLabelCount.set(k, e); }
const ctaFrequency = [...ctaLabelCount.values()].sort((a, b) => b.total - a.total || b.pages.size - a.pages.size).slice(0, 8).map(e => ({ label: e.label, total: e.total, pageCount: e.pages.size, pages: [...e.pages].slice(0, 6) }));
const headCount = new Map(); let headingsTotal = 0, upper = 0; for (const p of pages) for (const h of p.headings || []) { headingsTotal++; if (h.text && h.text === h.text.toUpperCase() && /[A-Z]/.test(h.text)) upper++; const k = h.text.trim().toLowerCase(); if (!k) continue; const e = headCount.get(k) || { text: h.text.trim(), total: 0, pages: new Set(), level: h.level }; e.total++; e.pages.add(p.slug); headCount.set(k, e); }
const headingFrequency = [...headCount.values()].filter(e => e.pages.size >= 3).sort((a, b) => b.total - a.total || b.pages.size - a.pages.size).slice(0, 20).map(e => ({ text: e.text, total: e.total, pageCount: e.pages.size, level: e.level }));
const voiceTable = { ctaFrequency, headingFrequency, toneMetrics: { headingsTotal, headingsUppercasePercent: Math.round(100 * upper / Math.max(1, headingsTotal)), distinctHeadings: headCount.size, distinctCtaLabels: ctaLabelCount.size } };
const anchor = headingFrequency[0]; let crossPromo = { detected: false, anchorHeading: null, cluster: null, pages: null, pageCount: 0, totalPages: pages.length };
if (anchor) { const anchorPages = pages.filter(p => (p.headings || []).some(h => h.text.trim().toLowerCase() === anchor.text.toLowerCase())); const cluster = headingFrequency.slice(0, 12).map(e => ({ ...e, overlap: anchorPages.filter(p => (p.headings || []).some(h => h.text.trim().toLowerCase() === e.text.toLowerCase())).length })).filter(e => e.overlap / anchorPages.length >= 0.6); if (cluster.length >= 2) crossPromo = { detected: true, anchorHeading: anchor.text, cluster: cluster.map(({ text, total, pageCount, overlap }) => ({ text, total, pageCount, overlap })), pages: anchorPages.map(p => p.slug), pageCount: anchorPages.length, totalPages: pages.length }; }
const voice = { heroHeadline: home?.heroHeadline || null, heroSubcopy: home?.heroLede || null, heroImage, heroMedium, primaryCTALabel: mainCtas[0]?.label || null, ctaSamples: ctaFrequency.slice(0, 6).map(c => c.label), navItems, footerHeadings, firstParagraph: (home?.body || [])[0] || null, tone: { guess: 'professional-warm', evidence: 'inferred: second-person address ("Se hva du kan spare!", "Har du tenkt på…"), short imperative CTAs ("Bli kunde", "Bruk min posisjon", "Søk boliglån"), plain-language explainers with check-lists; Norwegian bokmål; friendly flat illustrations', _provenance: 'inferred' } };
// ---------- logo / favicon / embeds / register ----------
const logoImg = (home?.media?.images || []).find(i => /logo/i.test((i.src || '') + (i.alt || '')) && i.rect && i.rect.top < 200 && i.rect.width > 0);
const logo = logoImg ? { source: 'img', sourceSelector: logoImg.domPath, url: logoImg.currentSrc || logoImg.src, localPath: existsSync(path.join(args.out, 'assets', 'logo.svg')) ? path.join(args.out, 'assets', 'logo.svg') : null, format: 'svg', intrinsicWidth: logoImg.naturalWidth, intrinsicHeight: logoImg.naturalHeight, renderedWidth: logoImg.rect.width, renderedHeight: logoImg.rect.height, alt: logoImg.alt, synthesized: false, synthesizedBasis: null } : { source: 'synthesized', synthesized: true, synthesizedBasis: 'no header logo image found' };
const crawlLog = existsSync(path.join(args.out, '_crawl-log.json')) ? JSON.parse(readFileSync(path.join(args.out, '_crawl-log.json'), 'utf8')) : {};
const favicon = crawlLog.favicon ? { source: 'favicon.ico', url: crawlLog.favicon.url, file: crawlLog.favicon.file } : null;
const embedDominated = pages.filter(p => p.embedDominance?.dominated).map(p => ({ slug: p.slug, iframeSrc: p.embedDominance.iframeSrc }));
const placeholderCount = pages.reduce((n, p) => n + (p.media?.images || []).filter(i => i.visible && (i.currentSrc || i.src || '').startsWith('data:')).length, 0);
const blocked = pages.reduce((n, p) => n + (p.media?.images || []).filter(i => i.visible && i.resolves === false && /^https?:/.test(i.currentSrc || i.src || '')).length, 0);
notes.push(`${placeholderCount} visible <img> elements sit on lazy-load data-URI placeholders at capture time (capture-state; replicate as captured, flag for delivery)`);
if (home && palette[0]) { const homeBg = (home.perSectionStyle || []).map(s => s.background?.color).filter(Boolean); const homeMode = homeBg.sort((a, b) => homeBg.filter(v => v === b).length - homeBg.filter(v => v === a).length)[0]; if (homeMode && parseColor(homeMode) && hex(parseColor(homeMode)) !== palette[0].value) notes.push(`home section-background mode ${hex(parseColor(homeMode))} differs from cross-page background ${palette[0].value}; cross-page value used`); }
const out = { _provenance: { writtenBy: 'stardust:extract (brand-surface.mjs, project script per brand-surface.md)', writtenAt: new Date().toISOString(), readArtifacts: pages.map(p => `stardust/current/pages/${p.slug}.json`).concat(['stardust/current/_fonts.json', 'stardust/current/assets/css/*.css']), synthesizedInputs: [], stardustVersion: '0.20.0', notes }, site: { name: 'Experian', tagline: home?.og?.description || home?.metaDescription || null, originUrl: args.origin }, origins: [{ origin: args.origin, role: 'primary', pagesCaptured: pages.length, contributedSignals: [] }], logo, favicon, palette, type, spacing, motifs, componentStyle, systemComponents: sys, iconFont, voice, voiceTable, crossPromo, embedDominatedPages: embedDominated, register: 'brand' };
writeFileSync(path.join(args.out, '_brand-extraction.json'), JSON.stringify(out, null, 2));
// summary
console.log('palette:'); for (const c of palette) console.log(`  ${c.role.padEnd(15)} ${c.value}  occ=${c.occurrences}  usedAs=${c.usedAs.join('/')}  src=${c.sources.join(',')}`);
console.log('dropped/accents:', paletteAll.slice(8).map(p => `${p.role}:${p.value}(${p.occurrences})`).join(' '));
console.log('\ntype: heading', headingFamily, '| body', bodyFamily, '| scale', type.scaleAudit.kind, matched, ratios.join(','));
for (const l of perLevel) console.log(`  h${l.level}: ${l.fontSize} w${l.fontWeight} lh ${l.lineHeight} ls ${l.letterSpacing} tt ${l.textTransform} (n=${l.count}, variants=${l.variants})`);
console.log('  body sizes:', type.bodyFamily.sizes, type.bodyFamily.lineHeights, '| textRendering:', JSON.stringify(textRenderingMode));
console.log('  font files:', files.length, files.map(f => `${path.basename(f.localPath)}[${f.family ? f.family.slice(0, 12) : '?'} ${f.weight || ''} ${f.licensingFlag}]`).join(', '));
console.log('\nspacing:', JSON.stringify(spacing));
console.log('\nmotifs radius:', JSON.stringify(motifs.borderRadius), '\nshadows:', motifs.shadows.map(s => s.value).join(' | '), '\ngradients:', motifs.gradients.length, '\npatterns:', patterns.map(p => p.name).join(', '));
console.log('\nbuttons:'); for (const v of componentStyle.buttons.allVariants.slice(0, 6)) console.log(`  ${v.background} on ${v.color} r=${v.borderRadius} pad=${v.padding} w${v.fontWeight} ${v.fontSize} border=${v.border} n=${v.occurrences}/${v.pages}p e.g. ${v.sampleLabels.slice(0, 3).join(' · ')}`);
console.log('\nsystem components:', sys.map(s => `${s.name} (${s.kind}, ${s.occurrences}p, ${s.linkCount ?? ''} links)`).join('; '));
console.log('iconFont:', iconFont ? `${iconFont.family} ${iconFont.glyphCount} glyphs` : null, '| logo:', logo.source, logo.url, `${logo.renderedWidth}x${logo.renderedHeight}`);
console.log('\nvoice:', JSON.stringify({ hero: voice.heroHeadline, lede: (voice.heroSubcopy || '').slice(0, 80), heroImage: voice.heroImage?.url?.slice(0, 80), primaryCTA: voice.primaryCTALabel, nav: voice.navItems, footer: voice.footerHeadings }, null, 0));
console.log('ctaFrequency:', ctaFrequency.map(c => `${c.label}(${c.total}/${c.pageCount}p)`).join(', '));
console.log('headingFrequency:', headingFrequency.slice(0, 8).map(h => `${h.text}(${h.total}/${h.pageCount}p)`).join(', '));
console.log('crossPromo:', crossPromo.detected, crossPromo.anchorHeading, crossPromo.pageCount, '| tone metrics:', JSON.stringify(voiceTable.toneMetrics), '| embed-dominated:', embedDominated.length);
console.log('\nnotes:'); notes.forEach(n => console.log(' -', n));
