// brand-review.mjs — extract Phase 5: render stardust/current/brand-review.html per reference/brand-review-template.md (canonical section order, mechanical Tensions detectors, brand-faithful chrome, single file, no JS).
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
const out = process.argv[2] || 'stardust/current';
const brand = JSON.parse(readFileSync(`${out}/_brand-extraction.json`, 'utf8'));
const design = JSON.parse(readFileSync(`${out}/DESIGN.json`, 'utf8'));
const log = JSON.parse(readFileSync(`${out}/_crawl-log.json`, 'utf8'));
const pages = readdirSync(`${out}/pages`).filter(f => f.endsWith('.json')).map(f => JSON.parse(readFileSync(`${out}/pages/${f}`, 'utf8')));
const product = readFileSync(`${out}/PRODUCT.md`, 'utf8');
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const hexToRgb = (h) => { const x = h.replace('#', ''); return { r: parseInt(x.slice(0, 2), 16), g: parseInt(x.slice(2, 4), 16), b: parseInt(x.slice(4, 6), 16) }; };
const sat = (h) => { const c = hexToRgb(h); return Math.max(c.r, c.g, c.b) - Math.min(c.r, c.g, c.b); };
const hue = (h) => { const { r, g, b } = hexToRgb(h); const R = r / 255, G = g / 255, B = b / 255, mx = Math.max(R, G, B), mn = Math.min(R, G, B), d = mx - mn; if (!d) return 0; let H = mx === R ? ((G - B) / d) % 6 : mx === G ? (B - R) / d + 2 : (R - G) / d + 4; return (H * 60 + 360) % 360; };
const lumin = (h) => { const { r, g, b } = hexToRgb(h); return 0.2126 * r + 0.7152 * g + 0.0722 * b; };
const darken = (h, f) => { const c = hexToRgb(h); return '#' + [c.r, c.g, c.b].map(v => Math.round(v * (1 - f)).toString(16).padStart(2, '0')).join(''); };
const pal = brand.palette;
const saturated = pal.filter(p => sat(p.value) > 30 && Math.max(...Object.values(hexToRgb(p.value))) < 240 && !['#000000', '#ffffff'].includes(p.value)).sort((a, b) => b.occurrences - a.occurrences);
const primary = saturated[0]?.value || pal.find(p => p.role === 'primary')?.value || '#147aff';
const hueDist = (a, b) => { const d = Math.abs(hue(a) - hue(b)); return Math.min(d, 360 - d); };
const primaryDark = saturated.find(p => p.value !== primary && hueDist(p.value, primary) <= 30 && lumin(p.value) < lumin(primary))?.value || darken(primary, 0.3);
const accent = saturated.find(p => p.value !== primary && p.value !== primaryDark && hueDist(p.value, primary) > 60)?.value || pal.find(p => p.role === 'secondary')?.value || primary;
const text = pal.find(p => p.role === 'text-primary')?.value || '#0f1217'; const textMuted = pal.find(p => p.role === 'text-secondary' || p.role === 'accent-1')?.value || '#667085';
const surface = '#ffffff', surfaceAlt = design.colors.coconut || '#f7f8fa', border = pal.find(p => p.role === 'border')?.value || '#e5e7eb';
const withFallback = (stack) => /sans-serif|serif|monospace/.test(stack || '') ? stack : `${stack}, -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif`;
const display = withFallback(brand.type.headingFamily.stack), body = withFallback(brand.type.bodyFamily.stack);
const upper = brand.voiceTable.toneMetrics.headingsUppercasePercent >= 25;
// ---- Tensions (mechanical) ----
const tensions = [];
const T = (id, title, bodyTxt, source, badge = 'observed') => tensions.push({ id, title, body: bodyTxt, source, badge });
if (brand.type.scaleAudit.kind === 'ad-hoc') T('T-scale', 'Type scale is ad-hoc', `${brand.type.headingFamily.sizes.join(' → ')}, no consistent ratio (${brand.type.scaleAudit.ratios.join(', ')}). Direct will need to decide whether the target adopts a modular scale.`, '_brand-extraction.json § type.scaleAudit', 'synthesized');
const smallRadii = Object.entries(brand.motifs.borderRadius.occurrences).filter(([v, n]) => parseFloat(v) < 16 && n >= 10); if (smallRadii.length > 2) T('T-radius-vocab', 'Radius vocabulary is fragmented', `${smallRadii.map(([v, n]) => `${v} (${n})`).join(', ')}. Direct will need to pick a single small-radius value or accept the variance.`, '_brand-extraction.json § motifs.borderRadius.occurrences');
const buckets = { 'see-more': ['see more', 'learn more', 'more info', 'more', 'read more', 'view more', 'discover more', 'explore'], start: ['get started', 'start now', 'start free', 'try it', 'try now', 'try free', 'try for free', 'begin'], contact: ['contact', 'contact us', 'get in touch', 'talk to us', 'reach out', 'say hello'], buy: ['buy now', 'purchase', 'order now', 'order', 'add to cart', 'checkout'], signup: ['sign up', 'signup', 'create account', 'register', 'join', 'subscribe'], donate: ['donate', 'donate now', 'give', 'give now', 'support us', 'contribute'], 'vague-here': ['here', 'click here', 'read this', 'this', 'more'] };
const ctaLabels = new Map(); for (const p of pages) for (const c of p.ctas || []) { const l = (c.label || '').trim().toLowerCase(); if (l) ctaLabels.set(l, (ctaLabels.get(l) || 0) + 1); }
for (const [b, members] of Object.entries(buckets)) { const hits = members.filter(m => ctaLabels.has(m)); if (hits.length >= 2) T('T-cta-vocab', `CTA voice is fragmented (${b})`, `${hits.map(h => `"${h}" (${ctaLabels.get(h)})`).join(', ')}. Direct will need to pick a canonical voice for ${b} affordances.`, 'pages/*.json#ctas[].label', 'cross-page'); }
const linkTexts = new Map(); const linkPages = new Map(); for (const p of pages) for (const l of [...(p.links?.internal || []), ...(p.links?.external || [])]) { const t = (l.text || '').trim().toLowerCase(); if (['here', 'click here', 'read this', 'more', 'this'].includes(t)) { linkTexts.set(t, (linkTexts.get(t) || 0) + 1); (linkPages.get(t) || linkPages.set(t, new Set()).get(t)).add(p.slug); } }
if (linkTexts.size) T('T-link-content-free', 'Content-free link labels in use', `${[...linkTexts.entries()].map(([t, n]) => `"${t}" ×${n} (e.g. ${[...linkPages.get(t)].slice(0, 2).join(', ')})`).join('; ')}. Accessibility issue — screen readers and crawlers cannot tell what these point to.`, 'pages/*.json#links', 'cross-page');
T('T-logo-variants', 'Single logo variant captured', `Only one logo variant captured (${brand.logo.source}: ${path.basename(brand.logo.url || '')}). The redesign will need a monochrome / inverted / SVG variant set; direct should plan that.`, '_brand-extraction.json § logo');
const imbalance = pal.filter(p => !['#000000', '#ffffff'].includes(p.value) && !/^text-/.test(p.role) && (p.usedAs.length === 1) && (p.usedAs[0] === 'text' || p.usedAs[0] === 'background'));
if (imbalance.length > 3) T('T-color-imbalance', 'Multiple palette colors used in only one context', `<ul>${imbalance.map(p => `<li>${p.value} (${p.role}) — ${p.usedAs[0]} only</li>`).join('')}</ul>`, '_brand-extraction.json § palette[].usedAs'); else for (const p of imbalance) T('T-color-imbalance', `Color ${p.value} (${p.role}) appears as ${p.usedAs[0]} only`, `Never as ${p.usedAs[0] === 'text' ? 'background/border/fill' : 'text/border'}. Direct will need to decide: drop, expand, or keep as accent.`, '_brand-extraction.json § palette[].usedAs');
const anyTokens = pages.some(p => (p.cssCustomProperties || []).length); if (!anyTokens) T('T-no-tokens', 'Site ships no design tokens', 'No CSS custom properties defined. The migration target will introduce tokens, which is a structural change worth calling out.', 'pages/*.json#cssCustomProperties');
const frameworkDefaults = { '#007bff': 'Bootstrap 4', '#0d6efd': 'Bootstrap 5', '#6c757d': 'Bootstrap', '#28a745': 'Bootstrap 4', '#198754': 'Bootstrap 5', '#17a2b8': 'Bootstrap 4', '#0dcaf0': 'Bootstrap 5', '#ffc107': 'Bootstrap', '#dc3545': 'Bootstrap' };
const tok = (pages[0].cssCustomProperties || []).concat(...pages.slice(1, 5).map(p => p.cssCustomProperties || [])); const tp = tok.find(t => /^--(bs-)?primary$/.test(t.name)); const paletteP = pal.find(p => p.role === 'primary')?.value; if (tp && frameworkDefaults[tp.value?.toLowerCase()] && paletteP && paletteP.toLowerCase() !== tp.value.toLowerCase()) T('T-tokens-unused', 'Design tokens defined but unused', `--primary ships as ${tp.value} (likely a ${frameworkDefaults[tp.value.toLowerCase()]} default) while the brand's actual primary is ${paletteP}.`, 'pages/*.json#cssCustomProperties + palette[primary]', 'synthesized');
let imgs = 0, empty = 0; const generic = new Map(); for (const p of pages) for (const i of p.media?.images || []) { if (!i.visible) continue; imgs++; const a = (i.alt ?? '').trim(); if (!a) empty++; if (['logo', 'image', 'picture', 'photo', 'img', 'icon'].includes(a.toLowerCase())) generic.set(a, (generic.get(a) || 0) + 1); }
if (generic.size) T('T-img-alt-generic', 'Generic alt-text present', `${[...generic.values()].reduce((a, b) => a + b, 0)} image(s) carry stock placeholder alt text (${[...generic.keys()].join(', ')}). Distinct from empty alt — these claim a label but the label is content-free.`, 'pages/*.json#media.images[].alt', 'cross-page');
if (imgs && empty / imgs >= 0.3) T('T-img-alt-empty', 'Empty alt text widespread', `${Math.round(100 * empty / imgs)}% of ${imgs} visible images carry empty alt text. Accessibility issue and a content-sourcing decision for direct.`, 'pages/*.json#media.images[].alt', 'cross-page');
const embedDom = pages.filter(p => p.embedDominance?.dominated); if (embedDom.length) T('T-embed-dominance', 'Embed-dominated page exists', `${embedDom.map(p => p.slug).join(', ')} have primary content inside a cross-origin embed.`, 'pages/*.json#embedDominance');
const navLabels = new Set((brand.voice.navItems || []).concat((pages[0].links?.internal || []).filter(l => l.region === 'header').map(l => l.text)).map(s => (s || '').toLowerCase().trim()));
const conflicts = [['donate', 'get help'], ['pricing', 'contact sales'], ['sign up', 'start free trial'], ['book a demo', 'talk to sales'], ['sign in', 'log in']]; for (const [a, b] of conflicts) if (navLabels.has(a) && navLabels.has(b)) T('T-nav-conflict', 'Two top-nav items compete for the same action', `Top-nav contains both "${a}" and "${b}". Direct should resolve which is primary.`, 'pages/index.json#links.internal[region=header]');
const temporal = /(anniversary|centennial|20\d\d edition|year-in-review)/i; if (temporal.test((brand.logo.url || '') + (brand.logo.alt || '') + (brand.voice.heroHeadline || ''))) T('T-temporal-mark', 'Temporal mark detected', 'A time-bound campaign reference appears in the logo or hero.', '_brand-extraction.json § logo/voice');
const contrast = (a, b) => { const L = (h) => { const c = hexToRgb(h); const f = (v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4; }; return 0.2126 * f(c.r) + 0.7152 * f(c.g) + 0.0722 * f(c.b); }; const [l1, l2] = [L(a), L(b)].sort((x, y) => y - x); return (l1 + 0.05) / (l2 + 0.05); };
const bg = pal.find(p => p.role === 'background')?.value || '#ffffff'; const cr = contrast(text, bg); let bodyText = text; if (cr < 4.5) { bodyText = '#0f1217'; T('T-contrast', 'Captured text on background fails WCAG AA', `${text} on ${bg} = ${cr.toFixed(2)}:1 (< 4.5:1). The review overrides body copy to #0f1217 on #ffffff.`, '_brand-extraction.json § palette'); }
// consolidation
const byId = {}; for (const t of tensions) (byId[t.id] = byId[t.id] || []).push(t);
const cards = []; for (const [id, list] of Object.entries(byId)) { if (list.length > 3) cards.push({ id, title: `${list[0].title.replace(/ \(.*\)$/, '')} (×${list.length})`, body: `<ul>${list.map(l => `<li>${l.body}</li>`).join('')}</ul>`, source: list[0].source, badge: list[0].badge }); else cards.push(...list); }
// ---- data for sections ----
const shots = pages.filter(p => existsSync(`${out}/assets/screenshots/${p.slug}.png`)).map(p => ({ slug: p.slug, title: p.title, path: `assets/screenshots/${p.slug}.png`, pathname: new URL(p.url).pathname }));
const waitAvg = Math.round(pages.reduce((a, p) => a + (p._provenance.waitMs || 0), 0) / pages.length);
const heroLine = brand.voice.heroHeadline; const tagline = pages.find(p => p.slug === 'index')?.og?.description || pages.find(p => p.slug === 'index')?.metaDescription;
const firstPara = brand.voice.firstParagraph;
const sec = (id, title, badges, inner, cls = '') => inner ? `<section id="${id}" class="${cls}"><h2>${esc(title)} ${badges.map(b => `<span class="badge">${b}</span>`).join('')}</h2>${inner}</section>` : '';
const badgeLegend = { observed: 'Frequency-counted from CSS across ≥3 pages. High confidence.', 'home-only': 'Sourced from a single page (the home page). Lower confidence.', 'cross-page': 'Aggregated across all extracted pages. High confidence.', inferred: 'Agent judgment from raw data. Lowest confidence.', synthesized: 'Constructed from extracted inputs into a higher-level claim.' };
const productSection = (name) => { const m = product.match(new RegExp(`## ${name}\\n([\\s\\S]*?)(?=\\n## |$)`)); return m ? m[1].trim() : null; };
const html = `<!doctype html><html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SpareBank 1 · Current state brand review</title>
<style>
:root{--primary:${primary};--primary-dark:${primaryDark};--accent:${accent};--secondary:${pal.find(p => p.role === 'secondary')?.value || accent};--text:${bodyText};--text-muted:${textMuted};--surface:${surface};--surface-alt:${surfaceAlt};--border:${border};--display:${display};--body:${body}}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:var(--body);color:var(--text);background:var(--surface);line-height:1.5;font-size:16px}
nav.top{position:sticky;top:0;z-index:10;background:var(--primary-dark);color:#fff;display:flex;flex-wrap:wrap;align-items:center;gap:4px 8px;padding:8px 24px;font-family:var(--display);text-transform:uppercase;letter-spacing:1.5px;font-size:12px}nav.top strong{margin-right:12px;font-weight:700}nav.top a{color:#fff;text-decoration:none;padding:6px 10px;border-radius:150px}nav.top a:hover{background:rgba(255,255,255,.18)}
main{max-width:1280px;margin:0 auto;padding:0 24px 64px}section{padding:40px 0;border-bottom:1px solid var(--border)}h1,h2,h3,h4,.badge,.pill,th,figcaption{font-family:var(--display)}${upper ? 'h1,h2,h3,h4,.badge,.pill{text-transform:uppercase}' : ''}h1{font-size:40px;margin:0 0 8px;line-height:1.1}h2{font-size:28px;margin:0 0 20px;display:flex;align-items:center;gap:10px;flex-wrap:wrap}h3{font-size:18px;margin:24px 0 8px}h4{margin:0 0 6px;font-size:16px}
.badge{font-size:11px;font-weight:700;letter-spacing:.5px;padding:3px 8px;border-radius:150px;background:var(--surface-alt);color:var(--primary-dark);border:1px solid var(--border);text-transform:uppercase}.badge.accent{background:var(--accent);color:#fff;border-color:var(--accent)}
.masthead{padding:56px 0 32px}.masthead .hero-line{font-family:var(--display);font-size:24px;color:var(--accent);margin:8px 0;font-weight:700}.masthead .tag{color:var(--text-muted);max-width:70ch}.masthead code{font-family:ui-monospace,Menlo,monospace;font-size:13px}
.stats{display:flex;gap:16px;flex-wrap:wrap}.stat{flex:1;min-width:220px;background:var(--surface-alt);border-radius:12px;padding:20px}.stat b{display:block;font-family:var(--display);font-size:28px;color:var(--primary-dark)}.stat span{color:var(--text-muted);font-size:14px}
.pages{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:16px}.pages figure{margin:0;background:var(--surface-alt);border-radius:12px;overflow:hidden;border:1px solid var(--border)}.pages img{width:100%;aspect-ratio:16/10;object-fit:cover;object-position:top;display:block;background:#fff}.pages figcaption{padding:8px 10px;font-size:12px}.pages figcaption code{display:block;color:var(--text-muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.swatches{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:16px}.swatch{border:1px solid var(--border);border-radius:12px;overflow:hidden;background:var(--surface)}.swatch .chip{height:96px}.swatch .meta{padding:12px}.swatch .role{font-family:var(--display);text-transform:uppercase;font-size:12px;letter-spacing:.5px;color:var(--primary-dark)}.swatch code{font-family:ui-monospace,Menlo,monospace;font-size:13px}.swatch small{color:var(--text-muted);display:block;margin-top:4px}.pill{display:inline-block;padding:3px 10px;border-radius:150px;background:var(--surface-alt);font-size:12px;margin:2px 2px 0 0;border:1px solid var(--border)}
.type-row{display:grid;grid-template-columns:260px 1fr;gap:16px;align-items:baseline;padding:14px 0;border-top:1px solid var(--border)}.type-row code{font-family:ui-monospace,Menlo,monospace;font-size:12px;color:var(--text-muted)}
.voice-card{background:var(--surface-alt);padding:20px 24px;border-radius:12px;margin:0 0 12px}.voice-card .lbl{font-family:var(--display);text-transform:uppercase;font-size:11px;letter-spacing:1px;color:var(--text-muted)}.voice-card p{margin:6px 0 0;font-size:18px}
table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--border);vertical-align:top}th{font-size:12px;text-transform:uppercase;letter-spacing:.5px;color:var(--text-muted)}
.two{display:grid;grid-template-columns:1fr 1fr;gap:24px}@media(max-width:720px){.two{grid-template-columns:1fr}.type-row{grid-template-columns:1fr}}
.tensions{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:720px){.tensions{grid-template-columns:1fr}}.tension{border-left:4px solid var(--accent);background:var(--surface-alt);padding:16px 18px;border-radius:0 12px 12px 0}.tension .tag{font-family:var(--display);font-size:11px;letter-spacing:.5px;color:var(--accent);font-weight:700}.tension h3{margin:4px 0 6px}.tension p,.tension ul{margin:0;font-size:14px}.tension .src{display:block;margin-top:8px;font-size:12px;color:var(--text-muted);font-family:ui-monospace,Menlo,monospace}
.motifs{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:16px}.motif{border:1px solid var(--border);border-radius:12px;padding:16px;text-align:center}.motif .box{width:72px;height:72px;margin:0 auto 10px;background:var(--primary)}.motif .shadow{background:var(--surface)}
.comp{border-left:3px solid var(--primary);padding:6px 14px;margin:8px 0;background:var(--surface);display:flex;justify-content:space-between;gap:12px}.comp span{color:var(--text-muted);font-size:13px}
.sys{border:1px solid var(--border);border-radius:12px;padding:14px 16px;margin:10px 0}.sys .kind{font-family:var(--display);text-transform:uppercase;font-size:11px;letter-spacing:.5px;color:var(--primary-dark)}
.logo-row{display:flex;gap:32px;align-items:flex-start;flex-wrap:wrap}.logo-row img{max-width:280px;background:var(--surface-alt);padding:16px;border-radius:12px}dl{display:grid;grid-template-columns:180px 1fr;gap:6px 16px;font-size:14px}dt{color:var(--text-muted)}dd{margin:0;min-width:0}code,p,li,small,dd,td,.stat span{overflow-wrap:anywhere}.logo-row img{max-width:100%}@media(max-width:720px){dl{grid-template-columns:1fr}.stats .stat{min-width:0}}
.bars{display:flex;gap:10px;align-items:flex-end;height:120px;margin:12px 0}.bars div{background:var(--primary);width:36px;border-radius:4px 4px 0 0;position:relative}.bars div span{position:absolute;bottom:-20px;left:0;right:0;text-align:center;font-size:11px;color:var(--text-muted)}
.btn-demo{display:inline-block;margin:6px 8px 6px 0;font-family:var(--body)}
footer{padding:32px 0;color:var(--text-muted);font-size:13px}footer .legend span{display:inline-block;margin-right:12px}
@media print{nav.top{position:static}section{break-inside:avoid}}
</style><!-- sb1-mobile-fix --><style>@media (max-width:600px){html,body{overflow-x:hidden!important;max-width:100vw}main,section,div{max-width:100%;min-width:0}.stats{display:grid!important;grid-template-columns:1fr 1fr!important}code,pre,dd,dt,td,th,figcaption,small{white-space:normal!important;word-break:break-all!important;overflow-wrap:anywhere!important;max-width:100%}table{display:block!important;overflow-x:auto!important;max-width:100%}img,svg{max-width:100%!important;height:auto}}</style></head><body>
<nav class="top"><strong>SpareBank 1 · Current state</strong>${['coverage', 'pages', 'palette', 'typography', 'voice', 'tensions', 'motifs', 'components', ...(brand.systemComponents.length ? ['system'] : []), 'logo', 'spacing'].map(s => `<a href="#${s}">${s}</a>`).join('')}</nav>
<main>
<header class="masthead"><h1>${esc(brand.site.name)} — current-state brand review</h1><p class="hero-line">${esc(heroLine)}</p><p class="tag">${esc(tagline)}</p><p><code>${esc(brand.site.originUrl)}</code> · ${pages.length} pages captured · extracted ${esc(log.crawl.startedAt?.slice(0, 10))}</p></header>
${sec('coverage', 'Coverage', ['observed'], `<div class="stats"><div class="stat"><b>${pages.length}</b><span>pages extracted (of ${log.discovery.discoveredCount.toLocaleString()} discovered; ${log.discovery.chromeLinksDiscovered} header/footer links) · Provenance ${pages.length}/${pages.length} live</span></div><div class="stat"><b>${esc(log.discovery.waitMode)}</b><span>wait strategy · avg ${waitAvg} ms · ${esc(log.discovery.fetchTechnique)} Chromium + recipe-completion style pass</span></div><div class="stat"><b>${pal.length} colors · ${brand.type.headingFamily.name}</b><span>${brand.type.files.length} font files · ${brand.iconFont ? brand.iconFont.glyphCount + ' icon glyphs' : 'no icon font'} · ${brand.systemComponents.length} system components · ${design.extensions.modules.length} module candidates</span></div></div>${log.crawl.failures.length ? `<p style="color:var(--accent)">Failures: ${log.crawl.failures.map(f => f.slug).join(', ')}</p>` : ''}<p style="color:var(--accent);font-size:14px">Capture-state notes: ${esc(brand._provenance.notes.filter(n => /403|placeholder/.test(n)).join(' · '))}. Vision check: ${log.visionCheck.filter(v => v.verdict === 'ok').length} ok, ${log.visionCheck.filter(v => v.verdict !== 'ok').length} suspect (${log.visionCheck.filter(v => v.verdict !== 'ok').map(v => v.slug).join(', ')}).</p>`)}
${sec('pages', 'Pages', ['observed'], `<div class="pages">${shots.map(s => `<figure><img src="${s.path}" alt="${esc(s.title)}" loading="lazy"><figcaption>${esc(s.title)}<code>${esc(s.pathname)}</code></figcaption></figure>`).join('')}</div>`)}
${sec('palette', 'Color palette', ['cross-page'], `<div class="swatches">${pal.map(p => `<div class="swatch"><div class="chip" style="background:${p.value}"></div><div class="meta"><div class="role">${esc(p.role)}</div><code>${p.value}</code><small>${p.occurrences.toLocaleString()} weighted occurrences</small><div>${p.usedAs.map(u => `<span class="pill">${u}</span>`).join('')}</div><small>${p.sources.map(esc).join(', ')}</small></div></div>`).join('')}</div><p style="font-size:13px;color:var(--text-muted)">${esc(brand._provenance.notes.find(n => /capped/.test(n)) || '')}</p>`)}
${sec('typography', 'Typography', ['cross-page', brand.type.scaleAudit.kind === 'modular' ? `modular ${brand.type.scaleAudit.matchedScale}` : 'No modular scale'], `${brand.type.headingFamily.perLevel.map(l => `<div class="type-row"><code>H${l.level} · ${esc(brand.type.headingFamily.name)} ${l.fontWeight} / ${l.fontSize} / ${l.lineHeight}${l.letterSpacing !== 'normal' ? ' / ' + l.letterSpacing : ''} · n=${l.count}</code><div style="font-family:var(--display);font-weight:${l.fontWeight};font-size:${l.fontSize};line-height:${l.lineHeight}">${esc(heroLine)}</div></div>`).join('')}<div class="type-row"><code>Body · ${esc(brand.type.bodyFamily.name)} 400 / ${brand.type.bodyFamily.sizes[0]} / ${brand.type.bodyFamily.lineHeights[0]}</code><p style="margin:0;font-size:${brand.type.bodyFamily.sizes[0]};line-height:${brand.type.bodyFamily.lineHeights[0]}">${esc(firstPara)}</p></div><div class="type-row"><code>Eyebrow · .eyebrow-text 700 / 12px / 0.08em uppercase</code><div style="font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase">Learn more about credit cards</div></div><p style="font-size:13px;color:var(--text-muted)">Text rendering: ${esc(JSON.stringify(brand.type.textRendering))}. Font files: ${brand.type.files.map(f => esc(path.basename(f.localPath))).join(', ')}.</p>`)}
${sec('voice', 'Voice', ['home-only', 'cross-page', `tone: ${esc(brand.voice.tone.guess)} (inferred)`], `<div class="voice-card"><div class="lbl">Hero headline</div><p>${esc(brand.voice.heroHeadline)}</p></div><div class="voice-card"><div class="lbl">Tagline (meta description)</div><p>${esc(tagline)}</p></div><div class="voice-card"><div class="lbl">First paragraph</div><p>${esc(firstPara)}</p></div><h3>CTA frequency (top 8)</h3><table><tr><th>Label</th><th>Total</th><th>Pages</th></tr>${brand.voiceTable.ctaFrequency.map(c => `<tr><td><span class="pill">${esc(c.label)}</span></td><td>${c.total}</td><td>${c.pageCount}</td></tr>`).join('')}</table><h3>Repeated headings (≥3 pages)</h3><div class="two"><ul>${brand.voiceTable.headingFrequency.slice(0, Math.ceil(brand.voiceTable.headingFrequency.length / 2)).map(h => `<li>H${h.level} “${esc(h.text)}” — ${h.total}× on ${h.pageCount} pages</li>`).join('')}</ul><ul>${brand.voiceTable.headingFrequency.slice(Math.ceil(brand.voiceTable.headingFrequency.length / 2)).map(h => `<li>H${h.level} “${esc(h.text)}” — ${h.total}× on ${h.pageCount} pages</li>`).join('')}</ul></div><div class="stats"><div class="stat"><b>${brand.voiceTable.toneMetrics.headingsUppercasePercent}%</b><span>headings uppercase</span></div><div class="stat"><b>${brand.voiceTable.toneMetrics.distinctHeadings.toLocaleString()}</b><span>distinct headings (of ${brand.voiceTable.toneMetrics.headingsTotal.toLocaleString()})</span></div><div class="stat"><b>${brand.voiceTable.toneMetrics.distinctCtaLabels}</b><span>distinct CTA labels</span></div></div><p style="font-size:13px;color:var(--text-muted)">Nav: ${brand.voice.navItems.map(esc).join(' · ')}. Tone evidence (inferred): ${esc(brand.voice.tone.evidence)}</p>`)}
${sec('tensions', 'Tensions', ['synthesized'], `<div class="tensions">${cards.map(c => `<div class="tension"><span class="tag">${c.id} · ${c.badge}</span><h3 style="margin:4px 0 6px;font-size:16px">${esc(c.title)}</h3><p>${c.body}</p><span class="src">Source: ${esc(c.source)}</span></div>`).join('')}</div>${cards.length ? '' : '<p>No tensions fired.</p>'}`)}
${sec('motifs', 'Motifs', ['cross-page'], `<div class="motifs">${Object.entries(brand.motifs.borderRadius.occurrences).map(([v, n]) => `<div class="motif"><div class="box" style="border-radius:${v}"></div><b>${v}</b><br><small>${n} occurrences</small></div>`).join('')}${brand.motifs.shadows.map(s => `<div class="motif"><div class="box shadow" style="box-shadow:${esc(s.value)};border:1px solid var(--border);border-radius:12px"></div><small style="font-family:ui-monospace,Menlo,monospace;font-size:10px;word-break:break-all">${esc(s.value)}</small></div>`).join('')}</div><h3>Signature flat illustrations (content/dam/SB1/illustrasjoner)</h3><div class="pages">${[...new Set(pages.flatMap(p => (p.media?.images || []).map(i => i.currentSrc || i.src || '')).filter(u => /\/content\/dam\/SB1\/illustrasjoner\//.test(u)))].slice(0, 8).map(u => `<figure><img src="${u}" alt="" style="aspect-ratio:1;object-fit:contain;background:#fff"><figcaption><code>${esc(path.basename(u))}</code></figcaption></figure>`).join('')}</div>`)}
${sec('components', 'Components', ['cross-page'], `${Object.entries(pages.reduce((a, p) => { for (const [k, v] of Object.entries(p.components || {})) { if (k === 'other' || !v.count) continue; a[k] = a[k] || { pages: 0, total: 0 }; a[k].pages++; a[k].total += v.count; } return a; }, {})).sort((a, b) => b[1].pages - a[1].pages).map(([k, v]) => `<div class="comp"><b>${esc(k)}</b><span>${v.pages} pages · ${v.total} instances</span></div>`).join('')}<h3>Patterns</h3><ul>${brand.motifs.patterns.map(p => `<li><b>${esc(p.name)}</b> — ${esc(p.evidence)}</li>`).join('')}</ul><h3>Buttons (observed clusters)</h3>${brand.componentStyle.buttons.allVariants.slice(0, 5).map(v => `<span class="btn-demo" style="background:${v.background};color:${v.color};border-radius:${esc(v.borderRadius)};padding:${esc(v.padding)};font-weight:${v.fontWeight};font-size:${esc(v.fontSize)};border:${esc(v.border)}">${esc(v.sampleLabels[0] || 'Button')}</span>`).join('')}<h3>Module candidates (${design.extensions.modules.length})</h3><div class="two"><ul>${design.extensions.modules.slice(0, Math.ceil(design.extensions.modules.length / 2)).map(m => `<li><b>${esc(m.id)}</b> <span class="pill">${esc(m.kind)}</span> ${m.instances} instances</li>`).join('')}</ul><ul>${design.extensions.modules.slice(Math.ceil(design.extensions.modules.length / 2)).map(m => `<li><b>${esc(m.id)}</b> <span class="pill">${esc(m.kind)}</span> ${m.instances} instances</li>`).join('')}</ul></div>`)}
${brand.crossPromo.detected ? sec('cross-promo', 'Cross-promo reproduction', ['cross-page'], `<div style="background:var(--primary-dark);border:4px dashed var(--primary);padding:24px;border-radius:12px;color:#fff"><span class="badge accent">Reproduction · approximate</span><h3 style="color:#fff">${esc(brand.crossPromo.anchorHeading)}</h3>${brand.crossPromo.cluster.map(c => `<div class="pill" style="background:rgba(255,255,255,.12);color:#fff;border-color:transparent">${esc(c.text)}</div>`).join('')}</div>`) : ''}
${sec('system', 'System components', ['cross-page'], brand.systemComponents.length ? brand.systemComponents.map(s => `<div class="sys"><span class="kind">${esc(s.kind)}</span> <b>${esc(s.name)}</b> — ${s.occurrences} pages${s.linkCount != null ? ` · ${s.linkCount} links` : ''}<br><small>${esc((s.headingSequence || []).slice(0, 10).join(' · ') || s.url || '')}</small>${s.ctaLabels?.length ? `<br><small>CTAs: ${s.ctaLabels.map(esc).join(' · ')}</small>` : ''}</div>`).join('') : null)}
${sec('logo', 'Logo & favicons', ['home-only'], `<div class="logo-row"><img src="assets/logo.svg" alt="SpareBank 1 logo"><dl><dt>Source</dt><dd>${esc(brand.logo.source)} · <code>${esc(brand.logo.sourceSelector)}</code></dd><dt>File</dt><dd>${esc(brand.logo.format)} · intrinsic ${brand.logo.intrinsicWidth}×${brand.logo.intrinsicHeight} · rendered ${brand.logo.renderedWidth}×${brand.logo.renderedHeight}</dd><dt>Variants captured</dt><dd>1 (primary color)</dd><dt>Variants not captured</dt><dd>white/inverted footer mark</dd><dt>Favicon</dt><dd>${esc(brand.favicon?.file)} ← ${esc(brand.favicon?.url)}</dd></dl></div>`)}
${sec('spacing', 'Spacing & shape', ['cross-page'], `<p>Base unit <b>${brand.spacing.baseUnit}px</b> · container <b>${esc(brand.spacing.containerMaxWidth)}</b> · section padding <b>${esc(brand.spacing.sectionPadding)}</b> (computed at 1440; CSS declares 64px base) · grid gap <b>${esc(brand.spacing.gridGap)}</b></p><div class="bars">${brand.spacing.scale.map(v => `<div style="height:${Math.min(100, v)}%"><span>${v}</span></div>`).join('')}</div><h3 style="margin-top:36px">Radii revisited</h3>${Object.keys(brand.motifs.borderRadius.occurrences).map(v => `<span class="pill" style="border-radius:${v}">${v}</span>`).join('')}`)}
${embedDom.length ? sec('embeds', 'Embed-dominated pages', ['observed'], embedDom.map(p => `<p>${esc(p.slug)} — ${esc(p.embedDominance.iframeSrc)}</p>`).join('')) : ''}
<footer><p>Provenance: rendered by stardust/scripts/brand-review.mjs from _brand-extraction.json, DESIGN.json, PRODUCT.md, _crawl-log.json, pages/*.json and assets/screenshots/. Chrome colors: --primary ${primary}, --primary-dark ${primaryDark}, --accent ${accent}.</p><p>What's next: this is a <b>same-design replica</b> — direction is preserved mechanically (stardust/direction.md), no <code>/stardust:direct</code> run.</p><p class="legend">${Object.entries(badgeLegend).map(([k, v]) => `<span><span class="badge">${k}</span> ${esc(v)}</span>`).join('')}</p></footer>
</main></body></html>`;
writeFileSync(`${out}/brand-review.html`, html);
console.log('brand-review.html written:', (html.length / 1024).toFixed(0), 'KB;', cards.length, 'tension cards:', cards.map(c => c.id).join(', '), '| chrome', { primary, primaryDark, accent });
