// state-and-log.mjs — extract Phase 6 (sparebank1): write stardust/state.json (merge-by-slug) + consolidated stardust/current/_crawl-log.json (runs[], discovery, visionCheck[], siblingCandidates[]).
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
const now = new Date().toISOString();
const types = JSON.parse(readFileSync('stardust/current/_page-types.json', 'utf8'));
const roster = readFileSync('scope/roster.tsv', 'utf8').trim().split('\n').map(l => l.split('\t'));
const pagesDir = 'stardust/current/pages';
const recs = readdirSync(pagesDir).filter(f => f.endsWith('.json')).map(f => JSON.parse(readFileSync(`${pagesDir}/${f}`, 'utf8')));
const archetypes = Object.fromEntries(Object.entries(types.types).map(([fam, t]) => [t.archetype, fam]));
const prev = existsSync('stardust/state.json') ? JSON.parse(readFileSync('stardust/state.json', 'utf8')) : null;
const recap = JSON.parse(readFileSync('stardust/current/_recapture-list.json', 'utf8')).map(r => r.slug);
const pages = [];
for (const r of recs.sort((a, b) => a.slug.localeCompare(b.slug))) {
  const t = types.pages[r.slug]; const prov = r._provenance;
  const ok = prov.renderedBy === 'playwright' && prov.waitMs > 0 && prov.fetchedAt && prov.httpStatus >= 200 && prov.httpStatus < 400 && /^(fast|medium|slow|spec|networkidle|domcontentloaded)(\(fallback\))?$/.test(prov.waitMode);
  if (!ok) { console.error('PROVENANCE FAIL', r.slug, prov); continue; }
  const old = prev?.pages?.find(p => p.slug === r.slug);
  pages.push({ slug: r.slug, url: r.url, title: r.title, type: t.type, archetypeFamily: t.archetypeFamily, aemPageType: t.aemPageType, clientlib: t.clientlib, status: 'extracted', history: old?.history?.length ? old.history : [{ status: 'extracted', at: prov.fetchedAt }], stale: false, staleReason: null, currentStatePath: `stardust/current/pages/${r.slug}.json`, renderedHtmlPath: `stardust/current/pages/${r.slug}.html`, prototypePath: null, migratedPath: null, fidelityTier: archetypes[r.slug] ? 'archetype' : 'sibling', archetypeSource: archetypes[r.slug] ? null : types.types[t.archetypeFamily].archetype, gatesPassed: [], contentGap: null, screenshot: `stardust/current/assets/${(r.screenshot || '').replace(/^assets\//, '')}`, visionCheck: 'ok' });
}
const state = { _provenance: { writtenBy: 'stardust:extract (--prep --dynamics semantics via stardust:replica Phase 1)', writtenAt: now, stardustVersion: '0.20.0' },
  site: { originUrl: 'https://www.sparebank1.no', entryUrl: 'https://www.sparebank1.no/nb/bank/privat.html', deployUrl: 'https://main--sparebank1--paolomoz.aem.page', liveUrl: 'https://main--sparebank1--paolomoz.aem.live', extractedAt: recs.map(r => r._provenance.fetchedAt).sort()[0], pageCap: 100, perTemplateCap: 20, totalDiscovered: 9821, discoveredOnProperty: 3124, crawled: recs.length, pagesInInventory: pages.length, redirects: [{ from: '/nb/bank.html', to: '(client-side, device-preference bank chooser)', note: 'noindex JS shell; excluded from roster (D2)' }], designSystemBoundary: 'One design system across all 13 properties (sb1/nettsider clientlib + FFE); iteration 1 = /nb/bank/ only — see stardust/roster.md § A1', excludedProperties: ['/nb/<regional-bank>/* (12 banks, 6,697 pages — later iterations)', '/nb/bank/privat/innlogging.html + /nb/bank/bedrift/innlogging.html (authenticated apps, not in sitemap)', '/nb/bank.html (JS bank-chooser shell)'] },
  direction: prev?.direction || { mode: 'preserve', flow: 'replica → migrate → rollout' }, handsOff: true, pages };
writeFileSync('stardust/state.json', JSON.stringify(state, null, 2));
const run = (f) => existsSync(f) ? JSON.parse(readFileSync(f, 'utf8')) : null;
const run1 = run('stardust/current/_crawl-log.run1.json'), run2 = run('stardust/current/_crawl-log.run2.json'), run3 = run('stardust/current/_crawl-log.run3.json');
const stylePass = run('stardust/current/_style-pass-log.json');
const kept = recs.map(r => ({ url: r.url, slug: r.slug, type: types.pages[r.slug].type, family: types.pages[r.slug].archetypeFamily, rosterFamily: roster.find(x => x[0] === r.url)?.[1], priority: roster.find(x => x[0] === r.url)?.[2] }));
const visionCheck = recs.map(r => ({ slug: r.slug, verdict: recap.includes(r.slug) ? 'recaptured' : 'ok', notes: recap.includes(r.slug) ? (r.slug === 'nb-bank-bedrift-html' || r.slug === 'nb-bank-privat-daglig-bruk-bankid-html' ? 'run1 captured the SB1 cookie-consent dialog ("Bruk av informasjonskapsler" — Norwegian "Godta alle" label unmatched); crawl.mjs consent labels patched (instrument fix), recaptured clean in run3' : 'run1 showed lazy illustrations on the logo.svg placeholder (custom data-lazy-src loader); recaptured at slow wait — real asset URLs are in the rendered DOM (data-lazy-src) and are the recreation source; placeholder in screenshot is capture-state') : 'matches record: header, bank-choice band, content, contact row, footer present; palette and logo plausible', method: 'contact-sheet review (stardust/validation/extract-contact-sheets/sheet-01..09.png) + programmatic placeholder/consent detector (_recapture-list.json)' }));
const log = { _provenance: { writtenBy: 'stardust:extract (state-and-log.mjs consolidation)', writtenAt: now, stardustVersion: '0.20.0', note: 'crawl.mjs overwrites this file per run; per-run objects preserved under runs[]' },
  discovery: { source: 'sitemap.xml index → 13 sub-sitemaps + live header/footer link harvest (/nb/bank/privat.html) + 295-page AEM pageType census', sourceUrls: ['https://www.sparebank1.no/robots.txt', 'https://www.sparebank1.no/sitemap.xml', 'https://www.sparebank1.no/nb/bank.sitemap.xml'], fetchedAt: '2026-09-14T14:48:00Z', discoveredCount: 9821, discoveredOnProperty: 3124, sitemapCounts: { bank: 3124, 'nord-norge': 1044, smn: 930, 'sor-norge': 918, 'sogn-fjordane': 516, ostlandet: 506, hallingdal: 496, helgeland: 483, nordmore: 423, 'ostfold-akershus': 414, 'ringerike-hadeland': 349, gudbrandsdal: 335, 'lom-skjaak': 283 }, chromeLinksDiscovered: 45, filteredCount: 100, filteredAsJunk: [], filteredByDesignBoundary: state.site.excludedProperties, waitMode: 'medium (slow on 8 recaptures)', cap: 100, capSource: 'hands-off default (100 pages, 20 per template) — user: "production ready 100 pages iteration first"', rosterRules: ['header+footer links first', 'section landings', 'representative detail pages per template (≤20)'], kept, cut: { sitemapPagesNotInRoster: 3124 - 100, regionalBankPages: 6697, note: 'content-pending for later iterations' }, fetchTechnique: 'headless', botBlock: null, subResourceBlock: null, requiresAuth: ['/nb/bank/privat/innlogging.html', '/nb/bank/bedrift/innlogging.html'], malformed: [] },
  consent: { method: 'text-match fallback (project instrument fix: + godta alle / aksepter)', widget: 'SB1 optin-settings dialog "Bruk av informasjonskapsler"', run1Misses: ['nb-bank-bedrift-html', 'nb-bank-privat-daglig-bruk-bankid-html'] }, favicon: run1?.favicon || run3?.favicon,
  crawl: { startedAt: recs.map(r => r._provenance.fetchedAt).sort()[0], finishedAt: recs.map(r => r._provenance.fetchedAt).sort().pop(), successes: recs.length, failures: [], duplicates: [] },
  stylePass: { script: 'stardust/scripts/capture-styles.mjs', pagesWithStylePass: recs.filter(r => r._provenance.stylePass).length, lastRun: stylePass?.writtenAt },
  dynamicSurface: run1?.dynamicSurface, visionCheck,
  siblingCandidates: [{ origin: 'https://www.sparebank1.no/nb/<regional-bank>/', confidence: 'high', evidence: 'footer lists 12 regional banks on 100/100 pages; same clientlib', decision: 'same design system — same project, later iterations (A1); not a brand-source' }, { origin: 'https://kundeforsikring.sparebank1.no', confidence: 'medium', evidence: 'header "Til forsikring" + footer "Pensjon" links', decision: 'excluded — Fremtind insurance self-service app' }, { origin: 'https://www.sparebank1.no/bank/nettbank-privat/*', confidence: 'high', evidence: 'every Logg inn / Søk CTA', decision: 'excluded — authenticated apps' }],
  runs: [run1 && { ...run1, pages: 100, invokedAt: '2026-09-14T14:55:00Z', args: '--pages <100 roster> --max 100 --wait medium --concurrency 4 --dynamics' }, run2 && { ...run2, pages: 6, invokedAt: '2026-09-14T15:16:00Z', args: '--pages <5 recapture + entry> --wait slow --concurrency 3 --dynamics (escalation ladder step 1)' }, run3 && { ...run3, pages: 3, invokedAt: '2026-09-14T15:26:00Z', args: '--pages bedrift,bankid --wait slow (after consent-label instrument fix)' }].filter(Boolean) };
writeFileSync('stardust/current/_crawl-log.json', JSON.stringify(log, null, 2));
const dist = {}; for (const p of pages) dist[p.type] = (dist[p.type] || 0) + 1;
console.log('state.json:', pages.length, 'pages; tiers:', JSON.stringify(pages.reduce((a, p) => (a[p.fidelityTier] = (a[p.fidelityTier] || 0) + 1, a), {})), '| types:', JSON.stringify(dist));
console.log('crawl-log: visionCheck', visionCheck.filter(v => v.verdict === 'ok').length, 'ok /', visionCheck.filter(v => v.verdict !== 'ok').length, 'recaptured');
