import { chromium } from 'playwright';
const file = 'file://' + process.cwd() + '/stardust/prototypes/round-01-danske-ramp/home.html';
const out = 'stardust/prototypes/round-01-danske-ramp/shots/';
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto(file, { waitUntil: 'networkidle' });
const y = await p.evaluate(() => { const r = document.querySelector('.router').getBoundingClientRect(), c = document.querySelector('.campaign').getBoundingClientRect(); return { router: r.bottom, campaign: c.bottom, rTop: r.top, cTop: c.top }; });
console.log('hero bottoms', y);
await p.screenshot({ path: out + 'h-hero-seam.png', clip: { x: 40, y: y.router - 40, width: 1360, height: 80 } });
await p.hover('.product:nth-child(2) .h3'); await p.waitForTimeout(600);
await p.screenshot({ path: out + 'h-product.png', clip: { x: 40, y: 400, width: 1360, height: 340 } });
await p.hover('.promo .btn'); await p.waitForTimeout(600);
const m = await p.locator('.membership').boundingBox();
await p.screenshot({ path: out + 'h-promo.png', clip: { x: 40, y: m.y - 10, width: 1360, height: m.height + 20 } });
const n = await p.locator('.news').boundingBox(); await p.mouse.move(300, n.y + 100); await p.waitForTimeout(800);
await p.screenshot({ path: out + 'h-news.png', clip: { x: 40, y: n.y - 10, width: 1360, height: n.height + 20 } });
const ch = p.locator('.channel summary').nth(1); await ch.scrollIntoViewIfNeeded(); await ch.hover(); await p.waitForTimeout(500);
const cb = await p.locator('.channels').boundingBox();
await p.screenshot({ path: out + 'h-channel.png', clip: { x: 40, y: cb.y - 10, width: 1360, height: cb.height + 20 } });
await p.evaluate(() => scrollTo(0, 0)); await p.hover('.router .h2-m'); await p.waitForTimeout(1000);
await p.screenshot({ path: out + 'h-router.png', clip: { x: 40, y: 100, width: 700, height: 480 } });
await b.close();
